AllCops:
  TargetRubyVersion: 2.7

# 以下アルファベット順に並べる
Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*.rb

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
