AllCops:
  TargetRubyVersion: 2.7

# 以下アルファベット順に並べる
Documentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - db/schema.rb

Layout/HashAlignment:
  Exclude:
    - lib/tasks/auto_annotate_models.rake

Layout/LineLength:
  Exclude:
    - db/schema.rb

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Lint/ConstantDefinitionInBlock:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*.rb

Metrics/BlockLength:
  Exclude:
    - db/schema.rb
    - lib/tasks/auto_annotate_models.rake
    - spec/**/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*.rb

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - db/schema.rb
