version: '3.1'
services:
  db:
    image: mysql:5.7
    env_file: .env
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
  web:
    build: .
    volumes:
      - .:/myapp
      - ./vendor/bundle:/usr/local/bundle
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    links:
      - db
