default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "hogehoge") %>
  host: db

development:
  <<: *default
  database: fp_matching_development

test:
  <<: *default
  database: fp_matching_test

production:
  <<: *default
  encoding: unicode
  database: fp_matching_production
  username: fp_matching
  password: <%= ENV['FP_MATCHING_DATABASE_PASSWORD'] %>
